services:
  web:
    image: muhammad532/my-web-app
    build: .
    ports:
      - "3001:3000"  # Now uses port 3001 externally
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s